#!/bin/sh
# SPDX-FileCopyrightText: 2025 Joost van der Laan
# SPDX-License-Identifier: AGPL-3.0-only

cargo fmt --all --check

if [ $? -ne 0 ]; then
  echo "Formatting check failed. Please run 'cargo fmt --all' and commit again."
  exit 1
fi

# Check REUSE compliance
echo "Checking REUSE compliance..."
reuse lint || exit 1
