# SPDX-FileCopyrightText: 2022 Félix Robles <felix@sequentech.io>
# SPDX-FileCopyrightText: 2022 X-Truder <jaka@x-truder.net>
# SPDX-FileCopyrightText: 2025 Joost van der Laan <joost@fashionunited.com>
#
# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-License-Identifier: MIT

# Reuse a base image made for devcontainers.
FROM ghcr.io/xtruder/nix-devcontainer:v1

# cache /nix
VOLUME /nix